--- #YAML:1.0
name:                Flickr-Upload
version:             1.32
abstract:            Module for uploading images to flickr.com
license:             ~
author:              
    - Christophe Beauregard <cpb@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Flickr::API:                   0.07
    Getopt::Long:                  1
    HTTP::Request::Common:         1
    LWP::UserAgent:                1
    Pod::Usage:                    1
    XML::Parser::Lite::Tree:       0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
